#Site Settings
permalink: pretty
title: nucleuscss
description: nucleuscss is a modular BEM and ITCSS framework
baseurl: 'https://mrjamesgrundy.github.io/nucleuscss/' # the subpath of your site, e.g. /blog/

#Build Settings
markdown: kramdown
